language: java
script: mvn clean compile package
deploy:
  provider: openshift
  user: jpercivall@42six.com
  password:
    secure: iiFj6fA46S08kz3VyfNR1G96Tej2deTdMrBnN/FypXiAD2oCVfR+4dyodqVg90kW3pnQz4a8ulvSzI1rnT6OmaRLWLmUc1SCtXrfT3mQQNhuTpUqVAvgrfi2EBOSZJfzR7VzFyk0Zy5zaa7GI8VThkNPO+xSz5+L1pWF+MDI46tmgN3Im4d+Tlo7P6ORE5N1MgxufZ+WFWLuVN3jlzwBCOOE1oJ8p3NkcyuDWPRqIJn556uj3sK6/9EZY2Xz1Z21ZE28KOyRgoLvUJqERTkDL430mSkjVSKZ3ccx+vSvVzDcX05o3Pp7DnT/oR8S1Dazx0241+NiDid+RMk/S/JRQZ06o47lUy6feTijxDHEj632ZVjd+Ls5KJQTrjjMf/mnNd6kcFYB1ud+FD3ofSEg/KKWD3jPqeNtlT40Mau8ZX3Eeojf2LBspw6pdmlcHXtyj9z9iQFXu5oCO/tN4+E1vNGn+wxVycf4p8+Ln30BEH4/5kJ3gsNhMSmheXsy/0e95qgX2p78Rv37vbcD6QRNPsn512G65izD+6/lpTHTQu8h0/TgqTw3Tlg24QBc01dHRGnDGcgrfeG29ybQfx1XRnYUHdZEah16QhEOBEWzFPPO7DULamIr9fOquroR/z4ZZPUaqYKvQsCrELO1ag2XENcoDweuvOmNg6uVksBAPOo=
  app: claire
  domain: 42six
  on:
    repo: 42sixsolutions/claire
