language: java
deploy:
  provider: openshift
  user: hochardga@gmail.com
  password:
    secure: rRLD2EoD2gkQCgS4Jm7+YIrK1V0P4AxZJcBB98FpoPIBDZHuXzt7kEWwITG6eqqjzH6xSqo5hVQrndjtoNmx3JMpKBgyfFJ3XsMWxvwPEqN8LVMj3AB3LfWAIS4Pc/Zx4gll4sgCvU9gBxOg2O6sN0sYq1c8W3XXxc/FyqNMJXikSr2KvWbwt5tGcQ1EWMWPdt/gHWoGMWr57I9UikppvM2XwgVQyn4nBb6Od5AAJOM1IQNWjb+9bV4PUmMDGCZBsA4Kd1UuDfFG0KyHtMGfAvDG5hV3znyKIhK7+w5ZUodbUW3hOdHASFGLM5LL9qO4FY5cVsf79ppOZiqNWNEUGnXbptmHcaa/JEQ964OFo0JlYcx+WVGse8iq0QCNARQsFrvkzlCLmNab6a4YvN8Vo3Os8m6V6mtpqP/CsccFlWEwx/RO5v7Jq1mljcrlwu49qPDZtINtaom++6yGLe5gcy9FJyfrsVijOCCmVT8Nfk8ljudqf8cwXWKFS/SBeYweM5a2yIi3fppnEuxTBNCp7yaOKuAGvSEOkjzVh41q/g1rNoCnf4gTdVCaMwPQkO+dLdcV9RuuLfIgGj+pu5a4IoB2FrjtNMKjS++jtqvPuEWe7GFwtW/410FmEmWbb8cgvhZoMjTqf7qCAT8EKVKDq2iXpV3YYCyPi2UZaQUeXwk=
  app: claire
  domain: 42six
  on:
    repo: 42sixsolutions/claire
before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
